REVOKE EXECUTE ON FUNCTION public.qualify_reservation_on_vdr() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_create_partner_reservation() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_promo_notification() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_analytics_log_capital_lead() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_analytics_log_signup() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_analytics_log_interest_lead() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_listing_vdr_readiness() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_listing_bootstrap_eb() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_partner_interest() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.eb_log_pipeline_transition() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_listing_codename() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_whatsapp_msg_touch_mandate() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_on_capital_request() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sla_deadline_setter() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_valuation_to_eb() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_lead_score_on_doc() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_partner_interest_response() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_buyer_profile_to_eb() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_capital_request_to_eb() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_interest_notification() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_message_notification() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_matching_buyers() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_match_providers() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.calculate_lead_score() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_whatsapp_msg_mirror_activity() FROM anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.recalculate_sv(p_cnpj text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.calculate_vdr_readiness(p_listing_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_request_disclosure(p_target_kind text, p_target_cnpj character varying, p_target_listing_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_upsert_mandate(p jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_health_summary_24h() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_executivo() FROM anon;
REVOKE EXECUTE ON FUNCTION public.qualify_lead(p_entity_type text, p_entity_id text, p_source text, p_notes text, p_promote_to_buyer boolean, p_promote_to_company boolean, p_buyer_profile jsonb, p_company_profile jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_nbo() FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_get_drain_job(p_job_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_mandato() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_match() FROM anon;
REVOKE EXECUTE ON FUNCTION public.expire_old_reservations() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_rate_limits() FROM anon;
REVOKE EXECUTE ON FUNCTION public.mari_ops_record_smoke(p_test_name text, p_status text, p_duration_ms integer, p_actual jsonb, p_message text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mari_ops_health_volume_recent(p_minutes integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_dismiss_today_card(p_card_kind text, p_ref_id uuid, p_reason text, p_snooze_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_decide_disclosure(p_request_id uuid, p_decision text, p_expires_in_days integer, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_health_recent_errors(limit_n integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_today_cards(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_open_whatsapp_action(p_draft_type text, p_draft_text_generated text, p_phone_number text, p_contact_id uuid, p_mandate_id uuid, p_buyer_id uuid, p_match_id uuid, p_suggested_action_label text, p_source text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_dashboard_kpis_v2() FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_dashboard_kpis() FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_match_crosstab(dim text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_log_whatsapp_send(p_mandate_id uuid, p_contact_id uuid, p_message_preview text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mari_ops_record_health(p_function_name text, p_status text, p_duration_ms integer, p_error_text text, p_payload_summary jsonb, p_request_id text, p_source text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_event_queue_stats() FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_mark_whatsapp_action(p_log_id uuid, p_marked_action text, p_draft_text_sent text, p_snooze_hours integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_store_advisor_token(p_advisor_id uuid, p_token text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_event_recent_errors(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.eb_log_deal_event(p_match_id uuid, p_event_type text, p_rejection_reason text, p_notes text, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.qualify_lead(p_entity_type text, p_entity_id text, p_source text, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_coverage() FROM anon;
REVOKE EXECUTE ON FUNCTION public.refresh_dashboard_views() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_mandate_field(p_mandate_id uuid, p_field text, p_value text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.approve_franchisee_request(p_request_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.approve_advisor_request(p_request_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reject_advisor_request(p_request_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reject_franchisee_request(p_request_id uuid, p_reason text) FROM anon;